/*
 * This source file was generated by the Gradle 'init' task
 */
// package app.src.main.java;

import app.src.main.java.Dosen.*;
import java.util.*;
public class App {
    public static void main(String[] args) {

        
        System.out.printf("Selamat nubes!!\n");

        
    }
}
