/*
 * This source file was generated by the Gradle 'init' task
 */
// package app.src.main.java;

import java.util.*;
import app.src.main.java.Creature.*;
import app.src.main.java.Zombies.*;

public class App {
    public static void main(String[] args) {

        NormalZombie zom1 = new NormalZombie();
        ConeheadZombie zom2 = new ConeheadZombie();
        PoleVaultingZombie zom3 = new PoleVaultingZombie();
        BucketheadZombie zom4 = new BucketheadZombie();
        DuckyTubeZombie zom5 = new DuckyTubeZombie();
        DolphinRiderZombie zom6 = new DolphinRiderZombie();
        zom1.displayZombie();
        zom2.displayZombie();
        zom3.displayZombie();
        zom4.displayZombie();
        zom5.displayZombie();
        zom6.displayZombie();
        //coba branch 
        Cherrybomb plan1 = new Cherrybomb();
        plan1.displayPlant();

        
    }
}
