/*
 * This source file was generated by the Gradle 'init' task
 */
// package app.src.main.java;

import MapGame.*;
import Sun.*;
import Plant.*;
import Zombies.*;


public class App {
    public static void main(String[] args) {

        NormalZombie zom1 = new NormalZombie();
        ConeheadZombie zom2 = new ConeheadZombie();
        PoleVaultingZombie zom3 = new PoleVaultingZombie();
        BucketheadZombie zom4 = new BucketheadZombie();
        DuckyTubeZombie zom5 = new DuckyTubeZombie();
        DolphinRiderZombie zom6 = new DolphinRiderZombie();
        SnorkelZombie zom7 = new SnorkelZombie();
        FlagZombie zom8 = new FlagZombie();
        ScreendoorZombie zom9 = new ScreendoorZombie();
        FootballZombie zom10 = new FootballZombie();
        zom1.displayZombie();
        zom2.displayZombie();
        zom3.displayZombie();
        zom4.displayZombie();
        zom5.displayZombie();
        zom6.displayZombie();
        zom7.displayZombie();
        zom8.displayZombie();
        zom9.displayZombie();
        zom10.displayZombie();
        System.out.println(" ");
        Sunflower pl1 = new Sunflower();
        Peashooter pl2 = new Peashooter();
        Wallnut pl3 = new Wallnut();
        SnowPea pl4 = new SnowPea();
        Squash pl5 = new Squash();
        Lilypad pl6 = new Lilypad();
        CherryBomb pl7 = new CherryBomb();
        Repeater pl8 = new Repeater();
        CabbagePult pl9 = new CabbagePult();
        TangleKelp pl10 = new TangleKelp();

        pl1.displayPlant();
        pl2.displayPlant();
        pl3.displayPlant();
        pl4.displayPlant();
        pl5.displayPlant();
        pl6.displayPlant();
        pl7.displayPlant();
        pl8.displayPlant();
        pl9.displayPlant();
        pl10.displayPlant();

        zom7.attack(pl3);
        pl3.displayPlant();

        pl2.attack(zom9);
        zom9.displayZombie();


        Peta peta = new Peta();
    

        Tile koor11 = peta.getTile(1, 4);
        Tile koor17 = peta.getTile(1, 7);

        peta.displayMap();

        // Menambahkan entitas ke GameMap pada posisi yang benar
        koor11.addCreature(pl10); // Tambah Sunflower ke Lawn
        koor17.addCreature(pl2); // Tambah Zombie ke ZombieSpaw
        koor11.addCreature(pl3);

        // Menampilkan GameMap
        System.out.println("GameMap after adding entities:");
        peta.displayMap(); // Menampilkan representasi GameMap

        System.out.println("GameMap after remove entities:");
        koor11.removeCreature(pl10);
        peta.displayMap();
        Sun matahari = new Sun();
        // matahari.SunGenerate();
        // System.out.println("Total Sun: " + matahari.getSun());
        //coba desktop

        
    }
}
